name: Python Tests

on:
  push:
    branches: [ main, master, pytest-branch ]
  pull_request:
    branches: [ main, master, pytest-branch ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest matplotlib numpy astropy gala celerite2 scipy
        pip install -e .

    - name: Run tests
      run: |
        pytest
